gText_TRProtect_The_World::
	.string "Prepare for trouble! And make it double!$"
gText_TRUnite_The_People::
	.string "To protect the world from devastation!$"
gText_TRTo_Denounce_Evil::
	.string "To unite all peoples within our nation!$"
gText_TRTo_Extend_Reach::
	.string "To denounce the evils of truth and\n"
	.string "love! To extend our reach to the stars\n"
	.string "above!$"
gText_TRJessie::
	.string "Jessie!$"
gText_TRJames::
	.string "James!$"
gText_TRBlast_Off::
	.string "Team Rocket blasts off at the speed of\n"
	.string "light! Surrender now, or prepare to\n"
	.string "fight!$"
gText_TRMeowth_Thats_Right::
	.string "Meowth! That's right!!$"
