#include "global.h"
#include "card.h"

static const u32 sCardBackGfx[]       = INCBIN_U32("graphics/cards/back.4bpp.lz");
static const u32 sCardChariotGfx[]    = INCBIN_U32("graphics/cards/chariot.4bpp.lz");
static const u32 sCardCoins1Gfx[]     = INCBIN_U32("graphics/cards/coins1.4bpp.lz");
static const u32 sCardCoins2Gfx[]     = INCBIN_U32("graphics/cards/coins2.4bpp.lz");
static const u32 sCardCoins3Gfx[]     = INCBIN_U32("graphics/cards/coins3.4bpp.lz");
static const u32 sCardCoins4Gfx[]     = INCBIN_U32("graphics/cards/coins4.4bpp.lz");
static const u32 sCardCoins5Gfx[]     = INCBIN_U32("graphics/cards/coins5.4bpp.lz");
static const u32 sCardCoins6Gfx[]     = INCBIN_U32("graphics/cards/coins6.4bpp.lz");
static const u32 sCardCoins7Gfx[]     = INCBIN_U32("graphics/cards/coins7.4bpp.lz");
static const u32 sCardCoins8Gfx[]     = INCBIN_U32("graphics/cards/coins8.4bpp.lz");
static const u32 sCardCups1Gfx[]      = INCBIN_U32("graphics/cards/cups1.4bpp.lz");
static const u32 sCardCups2Gfx[]      = INCBIN_U32("graphics/cards/cups2.4bpp.lz");
static const u32 sCardCups3Gfx[]      = INCBIN_U32("graphics/cards/cups3.4bpp.lz");
static const u32 sCardCups4Gfx[]      = INCBIN_U32("graphics/cards/cups4.4bpp.lz");
static const u32 sCardCups5Gfx[]      = INCBIN_U32("graphics/cards/cups5.4bpp.lz");
static const u32 sCardCups6Gfx[]      = INCBIN_U32("graphics/cards/cups6.4bpp.lz");
static const u32 sCardCups7Gfx[]      = INCBIN_U32("graphics/cards/cups7.4bpp.lz");
static const u32 sCardCups8Gfx[]      = INCBIN_U32("graphics/cards/cups8.4bpp.lz");
static const u32 sCardDeathGfx[]      = INCBIN_U32("graphics/cards/death.4bpp.lz");
static const u32 sCardDevilGfx[]      = INCBIN_U32("graphics/cards/devil.4bpp.lz");
static const u32 sCardEmperorGfx[]    = INCBIN_U32("graphics/cards/emperor.4bpp.lz");
static const u32 sCardEmpressGfx[]    = INCBIN_U32("graphics/cards/empress.4bpp.lz");
static const u32 sCardFoolGfx[]       = INCBIN_U32("graphics/cards/fool.4bpp.lz");
static const u32 sCardFortuneGfx[]    = INCBIN_U32("graphics/cards/fortune.4bpp.lz");
static const u32 sCardHangedmanGfx[]  = INCBIN_U32("graphics/cards/hangedman.4bpp.lz");
static const u32 sCardHermitGfx[]     = INCBIN_U32("graphics/cards/hermit.4bpp.lz");
static const u32 sCardHierophantGfx[] = INCBIN_U32("graphics/cards/hierophant.4bpp.lz");
static const u32 sCardJudgeGfx[]      = INCBIN_U32("graphics/cards/judge.4bpp.lz");
static const u32 sCardJusticeGfx[]    = INCBIN_U32("graphics/cards/justice.4bpp.lz");
static const u32 sCardLoversGfx[]     = INCBIN_U32("graphics/cards/lovers.4bpp.lz");
static const u32 sCardMagicianGfx[]   = INCBIN_U32("graphics/cards/magician.4bpp.lz");
static const u32 sCardMoonGfx[]       = INCBIN_U32("graphics/cards/moon.4bpp.lz");
static const u32 sCardPriestessGfx[]  = INCBIN_U32("graphics/cards/priestess.4bpp.lz");
static const u32 sCardStarGfx[]       = INCBIN_U32("graphics/cards/star.4bpp.lz");
static const u32 sCardStrengthGfx[]   = INCBIN_U32("graphics/cards/strength.4bpp.lz");
static const u32 sCardSunGfx[]        = INCBIN_U32("graphics/cards/sun.4bpp.lz");
static const u32 sCardSwords1Gfx[]    = INCBIN_U32("graphics/cards/swords1.4bpp.lz");
static const u32 sCardSwords2Gfx[]    = INCBIN_U32("graphics/cards/swords2.4bpp.lz");
static const u32 sCardSwords3Gfx[]    = INCBIN_U32("graphics/cards/swords3.4bpp.lz");
static const u32 sCardSwords4Gfx[]    = INCBIN_U32("graphics/cards/swords4.4bpp.lz");
static const u32 sCardSwords5Gfx[]    = INCBIN_U32("graphics/cards/swords5.4bpp.lz");
static const u32 sCardSwords6Gfx[]    = INCBIN_U32("graphics/cards/swords6.4bpp.lz");
static const u32 sCardSwords7Gfx[]    = INCBIN_U32("graphics/cards/swords7.4bpp.lz");
static const u32 sCardSwords8Gfx[]    = INCBIN_U32("graphics/cards/swords8.4bpp.lz");
static const u32 sCardTemperanceGfx[] = INCBIN_U32("graphics/cards/temperance.4bpp.lz");
static const u32 sCardTowerGfx[]      = INCBIN_U32("graphics/cards/tower.4bpp.lz");
static const u32 sCardWands1Gfx[]     = INCBIN_U32("graphics/cards/wands1.4bpp.lz");
static const u32 sCardWands2Gfx[]     = INCBIN_U32("graphics/cards/wands2.4bpp.lz");
static const u32 sCardWands3Gfx[]     = INCBIN_U32("graphics/cards/wands3.4bpp.lz");
static const u32 sCardWands4Gfx[]     = INCBIN_U32("graphics/cards/wands4.4bpp.lz");
static const u32 sCardWands5Gfx[]     = INCBIN_U32("graphics/cards/wands5.4bpp.lz");
static const u32 sCardWands6Gfx[]     = INCBIN_U32("graphics/cards/wands6.4bpp.lz");
static const u32 sCardWands7Gfx[]     = INCBIN_U32("graphics/cards/wands7.4bpp.lz");
static const u32 sCardWands8Gfx[]     = INCBIN_U32("graphics/cards/wands8.4bpp.lz");
static const u32 sCardWorldGfx[]      = INCBIN_U32("graphics/cards/world.4bpp.lz");

static const u16 sCardBackPal[]       = INCBIN_U16("graphics/cards/back.gbapal");
static const u16 sCardChariotPal[]    = INCBIN_U16("graphics/cards/chariot.gbapal");
static const u16 sCardCoinsPal[]      = INCBIN_U16("graphics/cards/coins.gbapal");
static const u16 sCardCupsPal[]       = INCBIN_U16("graphics/cards/cups.gbapal");
static const u16 sCardDeathPal[]      = INCBIN_U16("graphics/cards/death.gbapal");
static const u16 sCardDevilPal[]      = INCBIN_U16("graphics/cards/devil.gbapal");
static const u16 sCardEmperorPal[]    = INCBIN_U16("graphics/cards/emperor.gbapal");
static const u16 sCardEmpressPal[]    = INCBIN_U16("graphics/cards/empress.gbapal");
static const u16 sCardFoolPal[]       = INCBIN_U16("graphics/cards/fool.gbapal");
static const u16 sCardFortunePal[]    = INCBIN_U16("graphics/cards/fortune.gbapal");
static const u16 sCardHangedmanPal[]  = INCBIN_U16("graphics/cards/hangedman.gbapal");
static const u16 sCardHermitPal[]     = INCBIN_U16("graphics/cards/hermit.gbapal");
static const u16 sCardHierophantPal[] = INCBIN_U16("graphics/cards/hierophant.gbapal");
static const u16 sCardJudgePal[]      = INCBIN_U16("graphics/cards/judge.gbapal");
static const u16 sCardJusticePal[]    = INCBIN_U16("graphics/cards/justice.gbapal");
static const u16 sCardLoversPal[]     = INCBIN_U16("graphics/cards/lovers.gbapal");
static const u16 sCardMagicianPal[]   = INCBIN_U16("graphics/cards/magician.gbapal");
static const u16 sCardMoonPal[]       = INCBIN_U16("graphics/cards/moon.gbapal");
static const u16 sCardPriestessPal[]  = INCBIN_U16("graphics/cards/priestess.gbapal");
static const u16 sCardStarPal[]       = INCBIN_U16("graphics/cards/star.gbapal");
static const u16 sCardStrengthPal[]   = INCBIN_U16("graphics/cards/strength.gbapal");
static const u16 sCardSunPal[]        = INCBIN_U16("graphics/cards/sun.gbapal");
static const u16 sCardSwordsPal[]     = INCBIN_U16("graphics/cards/swords.gbapal");
static const u16 sCardTemperancePal[] = INCBIN_U16("graphics/cards/temperance.gbapal");
static const u16 sCardTowerPal[]      = INCBIN_U16("graphics/cards/tower.gbapal");
static const u16 sCardWandsPal[]      = INCBIN_U16("graphics/cards/wands.gbapal");
static const u16 sCardWorldPal[]      = INCBIN_U16("graphics/cards/world.gbapal");

const u32 * const gCardGfxs[CARD_COUNT] =
{
    [CARD_BACK]       = sCardBackGfx,
    [CARD_CHARIOT]    = sCardChariotGfx,
    [CARD_COINS1]     = sCardCoins1Gfx,
    [CARD_COINS2]     = sCardCoins2Gfx,
    [CARD_COINS3]     = sCardCoins3Gfx,
    [CARD_COINS4]     = sCardCoins4Gfx,
    [CARD_COINS5]     = sCardCoins5Gfx,
    [CARD_COINS6]     = sCardCoins6Gfx,
    [CARD_COINS7]     = sCardCoins7Gfx,
    [CARD_COINS8]     = sCardCoins8Gfx,
    [CARD_CUPS1]      = sCardCups1Gfx,
    [CARD_CUPS2]      = sCardCups2Gfx,
    [CARD_CUPS3]      = sCardCups3Gfx,
    [CARD_CUPS4]      = sCardCups4Gfx,
    [CARD_CUPS5]      = sCardCups5Gfx,
    [CARD_CUPS6]      = sCardCups6Gfx,
    [CARD_CUPS7]      = sCardCups7Gfx,
    [CARD_CUPS8]      = sCardCups8Gfx,
    [CARD_DEATH]      = sCardDeathGfx,
    [CARD_DEVIL]      = sCardDevilGfx,
    [CARD_EMPEROR]    = sCardEmperorGfx,
    [CARD_EMPRESS]    = sCardEmpressGfx,
    [CARD_FOOL]       = sCardFoolGfx,
    [CARD_FORTUNE]    = sCardFortuneGfx,
    [CARD_HANGEDMAN]  = sCardHangedmanGfx,
    [CARD_HERMIT]     = sCardHermitGfx,
    [CARD_HIEROPHANT] = sCardHierophantGfx,
    [CARD_JUDGE]      = sCardJudgeGfx,
    [CARD_JUSTICE]    = sCardJusticeGfx,
    [CARD_LOVERS]     = sCardLoversGfx,
    [CARD_MAGICIAN]   = sCardMagicianGfx,
    [CARD_MOON]       = sCardMoonGfx,
    [CARD_PRIESTESS]  = sCardPriestessGfx,
    [CARD_STAR]       = sCardStarGfx,
    [CARD_STRENGTH]   = sCardStrengthGfx,
    [CARD_SUN]        = sCardSunGfx,
    [CARD_SWORDS1]    = sCardSwords1Gfx,
    [CARD_SWORDS2]    = sCardSwords2Gfx,
    [CARD_SWORDS3]    = sCardSwords3Gfx,
    [CARD_SWORDS4]    = sCardSwords4Gfx,
    [CARD_SWORDS5]    = sCardSwords5Gfx,
    [CARD_SWORDS6]    = sCardSwords6Gfx,
    [CARD_SWORDS7]    = sCardSwords7Gfx,
    [CARD_SWORDS8]    = sCardSwords8Gfx,
    [CARD_TEMPERANCE] = sCardTemperanceGfx,
    [CARD_TOWER]      = sCardTowerGfx,
    [CARD_WANDS1]     = sCardWands1Gfx,
    [CARD_WANDS2]     = sCardWands2Gfx,
    [CARD_WANDS3]     = sCardWands3Gfx,
    [CARD_WANDS4]     = sCardWands4Gfx,
    [CARD_WANDS5]     = sCardWands5Gfx,
    [CARD_WANDS6]     = sCardWands6Gfx,
    [CARD_WANDS7]     = sCardWands7Gfx,
    [CARD_WANDS8]     = sCardWands8Gfx,
    [CARD_WORLD]      = sCardWorldGfx,
};

const u16 * const gCardPals[CARD_COUNT] =
{
    [CARD_BACK]       = sCardBackPal,
    [CARD_CHARIOT]    = sCardChariotPal,
    [CARD_COINS1]     = sCardCoinsPal,
    [CARD_COINS2]     = sCardCoinsPal,
    [CARD_COINS3]     = sCardCoinsPal,
    [CARD_COINS4]     = sCardCoinsPal,
    [CARD_COINS5]     = sCardCoinsPal,
    [CARD_COINS6]     = sCardCoinsPal,
    [CARD_COINS7]     = sCardCoinsPal,
    [CARD_COINS8]     = sCardCoinsPal,
    [CARD_CUPS1]      = sCardCupsPal,
    [CARD_CUPS2]      = sCardCupsPal,
    [CARD_CUPS3]      = sCardCupsPal,
    [CARD_CUPS4]      = sCardCupsPal,
    [CARD_CUPS5]      = sCardCupsPal,
    [CARD_CUPS6]      = sCardCupsPal,
    [CARD_CUPS7]      = sCardCupsPal,
    [CARD_CUPS8]      = sCardCupsPal,
    [CARD_DEATH]      = sCardDeathPal,
    [CARD_DEVIL]      = sCardDevilPal,
    [CARD_EMPEROR]    = sCardEmperorPal,
    [CARD_EMPRESS]    = sCardEmpressPal,
    [CARD_FOOL]       = sCardFoolPal,
    [CARD_FORTUNE]    = sCardFortunePal,
    [CARD_HANGEDMAN]  = sCardHangedmanPal,
    [CARD_HERMIT]     = sCardHermitPal,
    [CARD_HIEROPHANT] = sCardHierophantPal,
    [CARD_JUDGE]      = sCardJudgePal,
    [CARD_JUSTICE]    = sCardJusticePal,
    [CARD_LOVERS]     = sCardLoversPal,
    [CARD_MAGICIAN]   = sCardMagicianPal,
    [CARD_MOON]       = sCardMoonPal,
    [CARD_PRIESTESS]  = sCardPriestessPal,
    [CARD_STAR]       = sCardStarPal,
    [CARD_STRENGTH]   = sCardStrengthPal,
    [CARD_SUN]        = sCardSunPal,
    [CARD_SWORDS1]    = sCardSwordsPal,
    [CARD_SWORDS2]    = sCardSwordsPal,
    [CARD_SWORDS3]    = sCardSwordsPal,
    [CARD_SWORDS4]    = sCardSwordsPal,
    [CARD_SWORDS5]    = sCardSwordsPal,
    [CARD_SWORDS6]    = sCardSwordsPal,
    [CARD_SWORDS7]    = sCardSwordsPal,
    [CARD_SWORDS8]    = sCardSwordsPal,
    [CARD_TEMPERANCE] = sCardTemperancePal,
    [CARD_TOWER]      = sCardTowerPal,
    [CARD_WANDS1]     = sCardWandsPal,
    [CARD_WANDS2]     = sCardWandsPal,
    [CARD_WANDS3]     = sCardWandsPal,
    [CARD_WANDS4]     = sCardWandsPal,
    [CARD_WANDS5]     = sCardWandsPal,
    [CARD_WANDS6]     = sCardWandsPal,
    [CARD_WANDS7]     = sCardWandsPal,
    [CARD_WANDS8]     = sCardWandsPal,
    [CARD_WORLD]      = sCardWorldPal,
};
